RateStuff/Movies/urls.py
from django.urls import path
from . import views

app_name = "Movies"

urlpatterns = [
    path('', views.index, name='index'),
    path('MovieList/', views.view_movies, name='movie_list'),
    path('Add/', views.add_movie, name='add_movie')
]

RateStuff/RateStuff/urls.py
from django.contrib import admin
from django.urls import path, include
from Movies import views

urlpatterns = [
    path('', views.index),
    path('Movies/', include('Movies.urls')),
    path('admin/', admin.site.urls),
]

RateStuff/Movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=100)
    year = models.BigIntegerField()
    rating = models.DecimalField(max_digits=2, decimal_places=1)

RateStuff/Movies/forms.py
from django import forms
from Movies.models import Movie

class NewMovie(forms.ModelForm):
    class Meta():
        model = Movie
        fields = '__all__'

RateStuff/Movies/views.py
from django.shortcuts import render
from Movies.forms import NewMovie
from Movies.models import Movie

# Create your views here.
def index(request):
    return render(request, 'Movies/index.html')

def view_movies(request):
    movie_list = Movie.objects.all
    return render(request, 'Movies/movielist.html', {'movies':movie_list})

def add_movie(request):
    movie_form = NewMovie()

    if request.method == 'POST':
        movie_form = NewMovie(request.POST)
        if movie_form.is_valid():
            movie_form.save(commit=True)
            return index(request)
        else:
            print("From error.")

    return render(request, 'Movies/addmovie.html', {'movie_form':movie_form})

RateStuff/templates/Movies/addmovie.html
<!DOCTYPE html>
{% extends "Movies/base.html" %}
  {% block body_block %}

    <!-- add movie -->
    <div class="container">
      <h1>Add Movie</h1>
      <form class="form-horizontal" method="POST">
        <div class="form-group">
          {{ movie_form.as_p }}
          {% csrf_token %}
          <input type="submit" class='btn btn-primary' value="Submit">
        </div>
      </form>
    </div>
  {% endblock %}

RateStuff/templates/Movies/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
  </head>
  <body>

    <!-- nav bar -->
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
            <img alt="Brand" src="{% static "images/SampleLogo.png" %}">
          </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'Movies:index' %}">Home <span class="sr-only">(current)</span></a></li>
      </div>
    </nav>

    {% block body_block %}
    {% endblock %}

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

  </body>
</html>

RateStuff/templates/Movies/index.html
<!DOCTYPE html>
{% extends "movies/base.html" %}

  {% block body_block %}
    <!-- content -->
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to the Rating site</h1>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong>Actions</strong></h3>
          </div>
          <div class="panel-body">
            <div class="list-group">
              <a href="{% url 'Movies:movie_list' %}" class="list-group-item">
                <h3 class="list-group-item-heading">View</h3>
                <p class="list-group-item-text">Go to /Movies to view all movies</p>
              </a>
              <a href="{% url 'Movies:add_movie' %}" class="list-group-item">
                <h3 class="list-group-item-heading">Add</h3>
                <p class="list-group-item-text">Go to /Add to add movie</p>
              </a>
            </div>
          </div>
        </div>

      </div>
    </div>

  {% endblock %}

RateStuff/templates/Movies/movielist.html
<!DOCTYPE html>
{% extends "Movies/base.html" %}
  {% block body_block %}

    <!-- display movies -->
    {% if movies %}
    <div class="container">
      <h1>List of movies</h1>
      <table class="table table-striped table-condensed">
        <thead>
            <th>Name</th>
            <th>Year</th>
            <th>Rating</th>
        </thead>
        {% for movie in movies %}
        <tr>
          <td>{{movie.name}}</td>
          <td>{{movie.year}}</td>
          <td>{{movie.rating}}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
    {% else %}
      <p>No Movies</p>
    {% endif %}
  {% endblock %}